### ISSUE TITLE
Logger Error for --mode=val

### ISSUE THREAD

**Issue by rteehas** [clvrai/spirl#16]
Hi, I was trying to replicate the results by running in validation mode and got an error for the logger:

```
Traceback (most recent call last):
  File "spirl/rl/train.py", line 311, in <module>
    RLTrainer(args=get_args())
  File "spirl/rl/train.py", line 78, in __init__
    self.val()
  File "spirl/rl/train.py", line 162, in val
    self.logger, log_images=True, step=self.global_step)
  File "/home-nfs/rteehan/spirl/spirl/rl/components/agent.py", line 259, in log_outputs
    super().log_outputs(logging_stats, rollout_storage, logger, log_images, step)
  File "/home-nfs/rteehan/spirl/spirl/rl/components/agent.py", line 74, in log_outputs
    logger.log_scalar_dict(logging_stats, prefix='train' if self._is_train else 'val', step=step)
AttributeError: 'NoneType' object has no attribute 'log_scalar_dict'

```

Looking at the RLTrainer code, in the `self.setup_logging() ` function it only seems to set a logger for --mode=train and not for val.

**Comment by kpertsch** [comment]
Good catch! I never actually use the `--mode=val` option since the training code logs everything to wandb already. So I would recommend just running with `--mode=train` (which is the default) and then checking the resulting wandb plots.

If you still want to try running the val mode you could try to just remove the [if-statement](https://github.com/clvrai/spirl/blob/741d48722acb334be0f8fa542f6694e5392e59e9/spirl/rl/train.py#L253) in the `setup_logging()` function? I am not really sure why it is there in the first place.

**Comment by rteehas** [comment]
Thanks @kpertsch! For running in train vs. val mode, I noticed that during train the graphs reported in the paper (namely success/completed subtasks/blocks stacked) are not reported to wandb. Are they generated after the fact from those logs or should I be doing something else to get those curves?

**Comment by kpertsch** [comment]
Since our environments have sparse rewards, it is easy to translate the raw curves from WandB to the ones reported in the paper. E.g. we just need to apply binary thresholding on the maze rewards to get the success rate (since we only get reward if we solve the task) and the reward value in the kitchen is equivalent to the number of solved subtasks (since we get a reward of 1 for every solved subtask and no other rewards). But indeed we do this processing after the fact, not directly when reporting to WandB. We report success rate / number of subtasks in the paper mainly for better interpretability.

I hope this answers your question! Let me know if anything else is unclear! (and sorry for the long delay in answering -- I missed your follow-up question back then!)
