### ISSUE TITLE
parallel env

### ISSUE THREAD

**Issue by rainbow979** [clvrai/spirl#17]
Obvisiously, it is very slow to run one env at a time. But parallel env suffers from the problem of different steps in HRL especially fixed interval.
Would you have some ideas to solve this problem?

**Comment by kpertsch** [comment]
Hey, 
In our HRL setting the length of skills is fixed, ie the high-level policy will act at regular intervals (every 10 low-level steps in our case). Thus, running multiple environments in parallel is easy. 

In our implementation of parallelism we run 1 high-level policy step in each of the environments in parallel and then use the all the collected experience to update the agent, then rebroadcast the weights to all workers and repeat. This synchronous parallelization is relatively efficient since the skill length is fixed so the workers don't need to wait for each other a lot. If you had vastly different skill lengths between workers you might want to try asynchronous parallelization where updates are not blocked by any worker.

I am not sure whether I fully addressed your question. Please let me know if there are any other points you'd like to discuss!

**Comment by rainbow979** [comment]
Thanks for your complete reply.
What if there are two environment and steps of one is different than another, like 200 steps and 203 steps? 
Do you mean it needs to run high-level policy seperately in each environment?

**Comment by kpertsch** [comment]
Sorry for the delayed reply! Yes, right now the high-level policy is run in every environment separately (the environment interactions are performed in separate workers that sync the resulting transitions via MPI). 

In the case you mentioned the policies would indeed finish their HL action transitions at different times (since one can take the full 10 steps while the other terminates after 3 steps already) --> in this case the policy that does only 3 steps would wait for the one that does 10 steps. I think overall the efficiency loss because of this should be pretty small in our case, but if one wanted to be maximally efficient here one would need to implement asynchronous parallelism where no policy worker needs to wait for another. -- Since it was not a major efficiency concern for us here we did not look into implementing this though.
