### ISSUE TITLE
Caught RuntimeError in replica 1 on device 1.

### ISSUE THREAD

**Issue by gd-goblin** [clvrai/spirl#24]
Hi. 
I'm trying to learn a skill prior using my personal dataset.
It works well when using single GPU, but I got the following error when using multi-GPUs (two RTX 3090)

![Screenshot from 2022-04-18 19-10-59](https://user-images.githubusercontent.com/25500255/163793910-1edd29c3-9961-4879-a4eb-bc3cd40e9e3e.png)

How can I solve this?

**Comment by kpertsch** [comment]
Hi!
I haven't actually used multi-GPU training with the SPiRL models ever, so I am not sure how to solve the above issue. I would resort to single-GPU training if possible.

If you want to debug this, I would suggest to first remove the LSTM inference net (you can eg replace its output with a dummy zero-valued tensor) to see whether this is a problem specific to the recurrent architecture (the inference net is the only model component that uses an RNN).
If multi-GPU training works in the no-RNN case, you can replace the inference net RNN with an MLP -- this shouldn't be a problem since our skills are fixed length, so you can just concatenate the inputs from the fixed-length sequence and feed them into an MLP at once.

**Comment by gd-goblin** [comment]
After checking the training process, I realized that the loading dataset takes the most of time in each learning iteration.
(e.g. loading data takes 2.7s, logs takes 0.16s and actual computation takes 0.29s)

Thus using multi-GPU would not be expected to reduce the learning time as much as I expect.
Anyway, I will debug this later when multi-GPU is necessary :)

Thank you for your reply.

**Comment by kpertsch** [comment]
Re long loading times: you can try to move the data to an SSD if it's not already on one. Assuming that you are using SPiRL's h5 file loader, you should also try to keep the individual h5 files as small as possible. I usually have good loading times with individual files < 1MB. (eg remove images from the trajectories if you don't need them for training). Finally you can try increasing the number of data loading workers here: https://github.com/clvrai/spirl/blob/6a1cd84e7ae9ef38bcc983602cd3ab3421ca0991/spirl/components/data_loader.py#L30 (even though the default 8 is probably already high enough)
