### ISSUE TITLE
Kitchen enivronment observation is 60 instead of 30

### ISSUE THREAD

**Issue by gunnxx** [clvrai/spirl#30]
Hi, I am wondering whether including goal as an input is intentional. The SPIRL paper says that the kitchen environment has 30 states but running `python3 spirl/train.py --path=spirl/configs/skill_prior_learning/kitchen/hierarchical_cl --val_data_size=160` will include goal (observation becomes 60). I guess running RL also will have 60 observations because it uses `KitchenEnv` instead of `NoGoalKitchenEnv`.

**Comment by kpertsch** [comment]
Hi! If you check the dataset you can see that the goal is always constant, so we decided to just keep it as part of the input (the environment also returns the same goal, no matter which task you are trying to solve). Given this, I don't think there is a difference between running w/ vs w/o goal input.

Note however that if the goal would actually represent the goal the agent tried to achieve it would be important to *not* use it during pre-training since we want to learn task-agnostic skills that are transferrable to new tasks.

Thanks for bringing this up! I hope this answers your question.
