### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by NiranthS** [clvrai/spirl#4]
Hello @kpertsch 
First of all, Thanks a lot for this awesome work and documentation.
I am trying to set up the repo locally. When I tried to run train vanilla SAC on block_stacking environment, I am having the below error:
"RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x41 and 23x256)"

Resetting the environment is returning an observation of dimension 1x41
Could you please help in resolving this?

Thank You

**Comment by kpertsch** [comment]
Good catch! I accidentally copied the wrong config. I just fixed the data config and it should be running now, just pull the latest changes!

If it makes sense for your project I would recommend using the kitchen environment instead of block stacking: it allows you to test your algorithms on a more complex control problem with more diverse skills while enabling training from low-dim states for fast experimentation. + I just pushed [a new version of the SPiRL model](https://github.com/clvrai/spirl/blob/master/spirl/configs/skill_prior_learning/kitchen/hierarchical_cl/README.md) that improves performance on envs which require precise control, like the kitchen, so you could build off of that if you are planning to use SPiRL.

**Comment by NiranthS** [comment]
Thank you for the fix!

Actually, I am trying a new pipeline inspired by your work. To start with and have the pipeline ready, using the block_stacking one is easier in my case. Once the pipeline is ready, I will try with more complex environments.

The closed-loop one looks really good. I will try to build upon that. Thank you for the commit!
