### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: 

### ISSUE THREAD

**Issue by NiranthS** [clvrai/spirl#6]
Hello @kpertsch and @jesbu1 
I am having the following error when I tried to train a SAC with skill priors.
![Screenshot from 2021-04-13 02-04-20](https://user-images.githubusercontent.com/44475481/114458254-993e6880-9bfc-11eb-99bd-619fd195e2b2.png)
Could you please help me with this

**Comment by NiranthS** [comment]
It is happening just after some 4-5 training steps

**Comment by kpertsch** [comment]
Hi Niranth,

I haven't seen this error before. Can you send me the exact command & config you used that resulted in this error? Then I can try to reproduce it.
You said it already ran a couple of gradient steps successfully before the error occurred?

**Comment by NiranthS** [comment]
I used:

```
python3 spirl/rl/train.py --path=spirl/configs/hrl/block_stacking/spirl --seed=0 --prefix=SPIRL_block_stacking_seed0

```

Yes, every time it runs for 6-7 steps and then this error occurs.

**Comment by kpertsch** [comment]
Hi Niranth,

I debugged this today -- I think the problem is with the version of the pytorch package. When downloading the most recent pytorch package (1.8.X) I can reproduce your error. When downgrading to the version that I used while developing/testing the code (1.3.1) it seems to run fine. So option (1) for you is to downgrade pytorch to v1.3.1 (you will also need to downgrade torchvision to v0.4.2 to match it). I updated the `requirements.txt` to reflect the versions I tested the code with. One downside of this is that you might need to retrain your skill embedding models since the saving format for the checkpoints seems to have changed and I had trouble loading checkpoints trained with v1.8.X in RL code running on v1.3.1.

Alternatively the code also seems to run fine when moving [this](https://github.com/clvrai/spirl/blob/06a97c91507136bb69383845445204cf35f79e30/spirl/rl/agents/ac_agent.py#L152) line (the policy update) **above** the critic update in L144. In this case you could probably keep your old models, but I did not test whether the updated pytorch version messes with any of the other code.

Let me know if that resolves your issue!

**Comment by NiranthS** [comment]
This works!
Thanks a lot for the fixes
